AllCops:
  NewCops: enable
  SuggestExtensions: false

# This will acuse `expect {` from being bad style
Style/BlockDelimiters:
  Enabled: false

# We support ruby 1.8
Style/HashSyntax:
  Enabled: false

Style/Documentation:
  Enabled: false

# Missing magic comment
Style/FrozenStringLiteralComment:
  Enabled: false

# Freeze mutable objects assigned to constants.
Style/MutableConstant:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/ModuleLength:
  Max: 250

# Method has too many line
Metrics/MethodLength:
  Max: 25

# Block has too many lines
Metrics/BlockLength:
  Enabled: false
