version: 2.1

setup: &setup
  docker:
    - image: circleci/ruby:2.6.6
      environment:
        BUNDLER_VERSION: 2.2.0

commands:
  bundle:
    steps:
      - restore_cache:
          keys:
            - bundler-
      - run: gem install bundler
      - run:
          name: Install dependencies
          command: |
            bundle config set path 'vendor/bundle'
            bundle install
      - save_cache:
          key: bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

jobs:
  build:
    <<: *setup
    resource_class: small
    steps:
      - checkout
      - bundle
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Run spec
          command: bundle exec rspec
