version: 2.0

docker_images: &docker_images
  docker:
    - image: circleci/ruby:2.6.5-stretch-node-browsers

jobs:
  build:
    <<: *docker_images
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - xliffer-bundler-{{ checksum "Gemfile" }}
            - xliffer-bundler-
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - save_cache:
          key: xliffer-bundler-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Run spec
          command: bundle exec rspec
